[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
holder_metadata_plugin = "3DkEmKWuBJbza9ur1BnVVhXrzkuiMCqBuKHdoDBdLpxZ"
ai_aliens = "48MKwUN9uxxGrFCzXAV4kF5RPMVUyruLyYnapNynNtd4"
vending_machine = "Uvwz29jANqCpX5F2zMHo5NMZc5MdC23ss8gTUnsEJAY"
the_100 = "hundhVJRpUuamCdMthaPchfwEm2fiCpKgpxgUCNWXt9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 100000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[scripts]
test = "yarn run vitest run"

[workspace]
members = [
  "holder-metadata-plugin/program",
  "ai-aliens/program",
  "vending-machine/program",
  "the100/program",
]