[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
holder_metadata_plugin = "3DkEmKWuBJbza9ur1BnVVhXrzkuiMCqBuKHdoDBdLpxZ"
ai_aliens = "48MKwUN9uxxGrFCzXAV4kF5RPMVUyruLyYnapNynNtd4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jackson/.config/solana/id.json"

[scripts]
test = "yarn run mocha"

[workspace]
members = [
  "holder-metadata-plugin/program",
  "ai-aliens/program",
]