[package]
name = "field-authority-interface"
version = "0.3.3"
edition = "2021"

[dependencies]
solana-program = { workspace = true}
spl-token-metadata-interface =  { workspace = true}
borsh = { workspace = true}
thiserror = { workspace = true}
spl-discriminator = { workspace = true}