[package]
name = "gpl-common"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "gpl_common"

[features]
default = []

[dependencies]
anchor-lang = { workspace = true }
spl-token-metadata-interface = { workspace = true}