[package]
name = "gpl-util"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["lib"]
name = "gpl_util"

[features]
default = []

[dependencies]
anchor-lang = { workspace = true }